# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Big List of RPG Plots
author: S. John Ross
description: > # this means to ignore newlines until "baseurl:"
  Every RPG plot ever in the history of the whole world ever: An
  arbitrary exercise by S. John Ross. No GM can afford not to read this.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
keywords: >
  RPG, Adventure, Scenario, Plot, Dungeon, Adventures, Modules,
  Stories, Roleplaying, Roleplaying Game, GURPS, S. John Ross,
  Complete, AD&amp;D, Traveller, RuneQuest, Harn,
  World Of Darkness, Vampire

# Build settings
markdown: kramdown
